# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_invoice_items200_response import GetInvoiceItems200Response

class TestGetInvoiceItems200Response(unittest.TestCase):
    """GetInvoiceItems200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInvoiceItems200Response:
        """Test GetInvoiceItems200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInvoiceItems200Response`
        """
        model = GetInvoiceItems200Response()
        if include_optional:
            return GetInvoiceItems200Response(
                data = [
                    openapi_client.models.get_invoice_items_200_response_data_inner.get_invoice_items_200_response_data_inner(
                        amount = 20.2, 
                        from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        label = 'Linode 123', 
                        quantity = 4, 
                        region = 'us-west', 
                        tax = 1.25, 
                        to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total = 21.45, 
                        type = 'hourly', 
                        unit_price = '5.05', )
                    ],
                page = 1,
                pages = 1,
                results = 1
            )
        else:
            return GetInvoiceItems200Response(
        )
        """

    def testGetInvoiceItems200Response(self):
        """Test GetInvoiceItems200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
