# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_databases_mysql_instance_backups200_response_all_of_data_inner import GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner

class TestGetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner(unittest.TestCase):
    """GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner:
        """Test GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner`
        """
        model = GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner()
        if include_optional:
            return GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner(
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 123,
                label = 'Scheduled - 02/04/22 11:11 UTC-XcCRmI',
                type = 'auto'
            )
        else:
            return GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner(
        )
        """

    def testGetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner(self):
        """Test GetDatabasesMysqlInstanceBackups200ResponseAllOfDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
