# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.profile_api import ProfileApi


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfileApi()

    def tearDown(self) -> None:
        pass

    def test_delete_personal_access_token(self) -> None:
        """Test case for delete_personal_access_token

        Revoke a personal access token
        """
        pass

    def test_delete_profile_app(self) -> None:
        """Test case for delete_profile_app

        Revoke app access
        """
        pass

    def test_delete_profile_phone_number(self) -> None:
        """Test case for delete_profile_phone_number

        Delete a phone number
        """
        pass

    def test_delete_ssh_key(self) -> None:
        """Test case for delete_ssh_key

        Delete an SSH key
        """
        pass

    def test_delete_trusted_device(self) -> None:
        """Test case for delete_trusted_device

        Revoke a trusted device
        """
        pass

    def test_get_devices(self) -> None:
        """Test case for get_devices

        List trusted devices
        """
        pass

    def test_get_personal_access_token(self) -> None:
        """Test case for get_personal_access_token

        Get a personal access token
        """
        pass

    def test_get_personal_access_tokens(self) -> None:
        """Test case for get_personal_access_tokens

        List personal access tokens
        """
        pass

    def test_get_profile(self) -> None:
        """Test case for get_profile

        Get a profile
        """
        pass

    def test_get_profile_app(self) -> None:
        """Test case for get_profile_app

        Get an authorized app
        """
        pass

    def test_get_profile_apps(self) -> None:
        """Test case for get_profile_apps

        List authorized apps
        """
        pass

    def test_get_profile_grants(self) -> None:
        """Test case for get_profile_grants

        List grants
        """
        pass

    def test_get_profile_login(self) -> None:
        """Test case for get_profile_login

        Get a profile's login
        """
        pass

    def test_get_profile_logins(self) -> None:
        """Test case for get_profile_logins

        List logins
        """
        pass

    def test_get_security_questions(self) -> None:
        """Test case for get_security_questions

        List security questions
        """
        pass

    def test_get_ssh_key(self) -> None:
        """Test case for get_ssh_key

        Get an SSH key
        """
        pass

    def test_get_ssh_keys(self) -> None:
        """Test case for get_ssh_keys

        List SSH keys
        """
        pass

    def test_get_trusted_device(self) -> None:
        """Test case for get_trusted_device

        Get a trusted device
        """
        pass

    def test_get_user_preferences(self) -> None:
        """Test case for get_user_preferences

        Get user preferences
        """
        pass

    def test_post_add_ssh_key(self) -> None:
        """Test case for post_add_ssh_key

        Add an SSH key
        """
        pass

    def test_post_personal_access_token(self) -> None:
        """Test case for post_personal_access_token

        Create a personal access token
        """
        pass

    def test_post_profile_phone_number(self) -> None:
        """Test case for post_profile_phone_number

        Send a phone number verification code
        """
        pass

    def test_post_profile_phone_number_verify(self) -> None:
        """Test case for post_profile_phone_number_verify

        Verify a phone number
        """
        pass

    def test_post_security_questions(self) -> None:
        """Test case for post_security_questions

        Answer security questions
        """
        pass

    def test_post_tfa_confirm(self) -> None:
        """Test case for post_tfa_confirm

        Enable two factor authentication
        """
        pass

    def test_post_tfa_disable(self) -> None:
        """Test case for post_tfa_disable

        Disable two factor authentication
        """
        pass

    def test_post_tfa_enable(self) -> None:
        """Test case for post_tfa_enable

        Create a two factor secret
        """
        pass

    def test_put_personal_access_token(self) -> None:
        """Test case for put_personal_access_token

        Update a personal access token
        """
        pass

    def test_put_profile(self) -> None:
        """Test case for put_profile

        Update a profile
        """
        pass

    def test_put_ssh_key(self) -> None:
        """Test case for put_ssh_key

        Update an SSH key
        """
        pass

    def test_put_user_preferences(self) -> None:
        """Test case for put_user_preferences

        Update a user's preferences
        """
        pass


if __name__ == '__main__':
    unittest.main()
