# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_placement_groups200_response_data_inner_members_inner import GetPlacementGroups200ResponseDataInnerMembersInner

class TestGetPlacementGroups200ResponseDataInnerMembersInner(unittest.TestCase):
    """GetPlacementGroups200ResponseDataInnerMembersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPlacementGroups200ResponseDataInnerMembersInner:
        """Test GetPlacementGroups200ResponseDataInnerMembersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPlacementGroups200ResponseDataInnerMembersInner`
        """
        model = GetPlacementGroups200ResponseDataInnerMembersInner()
        if include_optional:
            return GetPlacementGroups200ResponseDataInnerMembersInner(
                is_compliant = True,
                linode_id = 123
            )
        else:
            return GetPlacementGroups200ResponseDataInnerMembersInner(
        )
        """

    def testGetPlacementGroups200ResponseDataInnerMembersInner(self):
        """Test GetPlacementGroups200ResponseDataInnerMembersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
