# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_rebuild_node_balancer_config_request_all_of_nodes_inner import PostRebuildNodeBalancerConfigRequestAllOfNodesInner

class TestPostRebuildNodeBalancerConfigRequestAllOfNodesInner(unittest.TestCase):
    """PostRebuildNodeBalancerConfigRequestAllOfNodesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostRebuildNodeBalancerConfigRequestAllOfNodesInner:
        """Test PostRebuildNodeBalancerConfigRequestAllOfNodesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostRebuildNodeBalancerConfigRequestAllOfNodesInner`
        """
        model = PostRebuildNodeBalancerConfigRequestAllOfNodesInner()
        if include_optional:
            return PostRebuildNodeBalancerConfigRequestAllOfNodesInner(
                address = '192.168.210.120:80',
                id = 54321,
                label = 'node54321',
                mode = 'accept',
                weight = 50
            )
        else:
            return PostRebuildNodeBalancerConfigRequestAllOfNodesInner(
        )
        """

    def testPostRebuildNodeBalancerConfigRequestAllOfNodesInner(self):
        """Test PostRebuildNodeBalancerConfigRequestAllOfNodesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
