# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.vpcs_api import VPCsApi


class TestVPCsApi(unittest.TestCase):
    """VPCsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VPCsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_vpc(self) -> None:
        """Test case for delete_vpc

        Delete a VPC
        """
        pass

    def test_delete_vpc_subnet(self) -> None:
        """Test case for delete_vpc_subnet

        Delete a VPC subnet
        """
        pass

    def test_get_vpc(self) -> None:
        """Test case for get_vpc

        Get a VPC
        """
        pass

    def test_get_vpc_ips(self) -> None:
        """Test case for get_vpc_ips

        List a VPC's IP addresses
        """
        pass

    def test_get_vpc_subnet(self) -> None:
        """Test case for get_vpc_subnet

        Get a VPC subnet
        """
        pass

    def test_get_vpc_subnets(self) -> None:
        """Test case for get_vpc_subnets

        List VPC subnets
        """
        pass

    def test_get_vpcs(self) -> None:
        """Test case for get_vpcs

        List VPCs
        """
        pass

    def test_get_vpcs_ips(self) -> None:
        """Test case for get_vpcs_ips

        List VPC IP addresses
        """
        pass

    def test_post_vpc(self) -> None:
        """Test case for post_vpc

        Create a VPC
        """
        pass

    def test_post_vpc_subnet(self) -> None:
        """Test case for post_vpc_subnet

        Create a VPC subnet
        """
        pass

    def test_put_vpc(self) -> None:
        """Test case for put_vpc

        Update a VPC
        """
        pass

    def test_put_vpc_subnet(self) -> None:
        """Test case for put_vpc_subnet

        Update a VPC subnet
        """
        pass


if __name__ == '__main__':
    unittest.main()
