# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_transfer200_response_region_transfers_inner import GetTransfer200ResponseRegionTransfersInner

class TestGetTransfer200ResponseRegionTransfersInner(unittest.TestCase):
    """GetTransfer200ResponseRegionTransfersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTransfer200ResponseRegionTransfersInner:
        """Test GetTransfer200ResponseRegionTransfersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransfer200ResponseRegionTransfersInner`
        """
        model = GetTransfer200ResponseRegionTransfersInner()
        if include_optional:
            return GetTransfer200ResponseRegionTransfersInner(
                billable = 0,
                id = 'us-east',
                quota = 5010,
                used = 1
            )
        else:
            return GetTransfer200ResponseRegionTransfersInner(
        )
        """

    def testGetTransfer200ResponseRegionTransfersInner(self):
        """Test GetTransfer200ResponseRegionTransfersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
