# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.added_post_promo_credit import AddedPostPromoCredit

class TestAddedPostPromoCredit(unittest.TestCase):
    """AddedPostPromoCredit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddedPostPromoCredit:
        """Test AddedPostPromoCredit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddedPostPromoCredit`
        """
        model = AddedPostPromoCredit()
        if include_optional:
            return AddedPostPromoCredit(
                promo_code = '0'
            )
        else:
            return AddedPostPromoCredit(
                promo_code = '0',
        )
        """

    def testAddedPostPromoCredit(self):
        """Test AddedPostPromoCredit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
