# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_domain(self) -> None:
        """Test case for delete_domain

        Delete a domain
        """
        pass

    def test_delete_domain_record(self) -> None:
        """Test case for delete_domain_record

        Delete a domain record
        """
        pass

    def test_get_domain(self) -> None:
        """Test case for get_domain

        Get a domain
        """
        pass

    def test_get_domain_record(self) -> None:
        """Test case for get_domain_record

        Get a domain record
        """
        pass

    def test_get_domain_records(self) -> None:
        """Test case for get_domain_records

        List domain records
        """
        pass

    def test_get_domain_zone(self) -> None:
        """Test case for get_domain_zone

        Get a domain zone file
        """
        pass

    def test_get_domains(self) -> None:
        """Test case for get_domains

        List domains
        """
        pass

    def test_post_clone_domain(self) -> None:
        """Test case for post_clone_domain

        Clone a domain
        """
        pass

    def test_post_domain(self) -> None:
        """Test case for post_domain

        Create a domain
        """
        pass

    def test_post_domain_record(self) -> None:
        """Test case for post_domain_record

        Create a domain record
        """
        pass

    def test_post_import_domain(self) -> None:
        """Test case for post_import_domain

        Import a domain
        """
        pass

    def test_put_domain(self) -> None:
        """Test case for put_domain

        Update a domain
        """
        pass

    def test_put_domain_record(self) -> None:
        """Test case for put_domain_record

        Update a domain record
        """
        pass


if __name__ == '__main__':
    unittest.main()
