# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.put_domain_record_request import PutDomainRecordRequest

class TestPutDomainRecordRequest(unittest.TestCase):
    """PutDomainRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutDomainRecordRequest:
        """Test PutDomainRecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutDomainRecordRequest`
        """
        model = PutDomainRecordRequest()
        if include_optional:
            return PutDomainRecordRequest(
                name = 'test',
                port = 80,
                priority = 50,
                protocol = '',
                service = '',
                tag = 'issue',
                target = '192.0.2.0',
                ttl_sec = 604800,
                weight = 50
            )
        else:
            return PutDomainRecordRequest(
        )
        """

    def testPutDomainRecordRequest(self):
        """Test PutDomainRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
