# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_domain_zone200_response import GetDomainZone200Response

class TestGetDomainZone200Response(unittest.TestCase):
    """GetDomainZone200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDomainZone200Response:
        """Test GetDomainZone200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDomainZone200Response`
        """
        model = GetDomainZone200Response()
        if include_optional:
            return GetDomainZone200Response(
                zone_file = ["; example.com [123]","$TTL 864000","@  IN  SOA  ns1.linode.com. user.example.com. 2021000066 14400 14400 1209600 86400","@    NS  ns1.linode.com.","@    NS  ns2.linode.com.","@    NS  ns3.linode.com.","@    NS  ns4.linode.com.","@    NS  ns5.linode.com."]
            )
        else:
            return GetDomainZone200Response(
        )
        """

    def testGetDomainZone200Response(self):
        """Test GetDomainZone200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
