# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_replicate_image_request import PostReplicateImageRequest

class TestPostReplicateImageRequest(unittest.TestCase):
    """PostReplicateImageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostReplicateImageRequest:
        """Test PostReplicateImageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostReplicateImageRequest`
        """
        model = PostReplicateImageRequest()
        if include_optional:
            return PostReplicateImageRequest(
                regions = ["us-iad","us-west"]
            )
        else:
            return PostReplicateImageRequest(
        )
        """

    def testPostReplicateImageRequest(self):
        """Test PostReplicateImageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
