# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_managed_credential_username_password_request import PostManagedCredentialUsernamePasswordRequest

class TestPostManagedCredentialUsernamePasswordRequest(unittest.TestCase):
    """PostManagedCredentialUsernamePasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostManagedCredentialUsernamePasswordRequest:
        """Test PostManagedCredentialUsernamePasswordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostManagedCredentialUsernamePasswordRequest`
        """
        model = PostManagedCredentialUsernamePasswordRequest()
        if include_optional:
            return PostManagedCredentialUsernamePasswordRequest(
                password = 's3cur3P@ssw0rd',
                username = 'johndoe'
            )
        else:
            return PostManagedCredentialUsernamePasswordRequest(
                password = 's3cur3P@ssw0rd',
        )
        """

    def testPostManagedCredentialUsernamePasswordRequest(self):
        """Test PostManagedCredentialUsernamePasswordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
