# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_notifications200_response_data_inner_entity import GetNotifications200ResponseDataInnerEntity

class TestGetNotifications200ResponseDataInnerEntity(unittest.TestCase):
    """GetNotifications200ResponseDataInnerEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNotifications200ResponseDataInnerEntity:
        """Test GetNotifications200ResponseDataInnerEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNotifications200ResponseDataInnerEntity`
        """
        model = GetNotifications200ResponseDataInnerEntity()
        if include_optional:
            return GetNotifications200ResponseDataInnerEntity(
                id = 3456,
                label = 'Linode not booting.',
                type = 'ticket',
                url = '/support/tickets/3456'
            )
        else:
            return GetNotifications200ResponseDataInnerEntity(
        )
        """

    def testGetNotifications200ResponseDataInnerEntity(self):
        """Test GetNotifications200ResponseDataInnerEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
