# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_events200_response_data_inner_entity import GetEvents200ResponseDataInnerEntity

class TestGetEvents200ResponseDataInnerEntity(unittest.TestCase):
    """GetEvents200ResponseDataInnerEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEvents200ResponseDataInnerEntity:
        """Test GetEvents200ResponseDataInnerEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEvents200ResponseDataInnerEntity`
        """
        model = GetEvents200ResponseDataInnerEntity()
        if include_optional:
            return GetEvents200ResponseDataInnerEntity(
                id = 11111,
                label = 'Problem booting my Linode',
                type = 'ticket',
                url = '/v4/support/tickets/11111'
            )
        else:
            return GetEvents200ResponseDataInnerEntity(
        )
        """

    def testGetEvents200ResponseDataInnerEntity(self):
        """Test GetEvents200ResponseDataInnerEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
