# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.linode_backups import LinodeBackups

class TestLinodeBackups(unittest.TestCase):
    """LinodeBackups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinodeBackups:
        """Test LinodeBackups
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinodeBackups`
        """
        model = LinodeBackups()
        if include_optional:
            return LinodeBackups(
                available = True,
                enabled = True,
                last_successful = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                schedule = openapi_client.models.linode_backups_schedule.Linode_backups_schedule(
                    day = 'Saturday', 
                    window = 'W22', )
            )
        else:
            return LinodeBackups(
        )
        """

    def testLinodeBackups(self):
        """Test LinodeBackups"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
