# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.node_balancers_api import NodeBalancersApi


class TestNodeBalancersApi(unittest.TestCase):
    """NodeBalancersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodeBalancersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_node_balancer(self) -> None:
        """Test case for delete_node_balancer

        Delete a NodeBalancer
        """
        pass

    def test_delete_node_balancer_config(self) -> None:
        """Test case for delete_node_balancer_config

        Delete a config
        """
        pass

    def test_delete_node_balancer_config_node(self) -> None:
        """Test case for delete_node_balancer_config_node

        Delete a NodeBalancer's node
        """
        pass

    def test_get_node_balancer(self) -> None:
        """Test case for get_node_balancer

        Get a NodeBalancer
        """
        pass

    def test_get_node_balancer_config(self) -> None:
        """Test case for get_node_balancer_config

        Get a config
        """
        pass

    def test_get_node_balancer_config_nodes(self) -> None:
        """Test case for get_node_balancer_config_nodes

        List nodes
        """
        pass

    def test_get_node_balancer_configs(self) -> None:
        """Test case for get_node_balancer_configs

        List configs
        """
        pass

    def test_get_node_balancer_firewalls(self) -> None:
        """Test case for get_node_balancer_firewalls

        List NodeBalancer firewalls
        """
        pass

    def test_get_node_balancer_node(self) -> None:
        """Test case for get_node_balancer_node

        Get a NodeBalancer's node
        """
        pass

    def test_get_node_balancer_stats(self) -> None:
        """Test case for get_node_balancer_stats

        Get NodeBalancer statistics
        """
        pass

    def test_get_node_balancer_types(self) -> None:
        """Test case for get_node_balancer_types

        List NodeBalancer types
        """
        pass

    def test_get_node_balancers(self) -> None:
        """Test case for get_node_balancers

        List NodeBalancers
        """
        pass

    def test_post_node_balancer(self) -> None:
        """Test case for post_node_balancer

        Create a NodeBalancer
        """
        pass

    def test_post_node_balancer_config(self) -> None:
        """Test case for post_node_balancer_config

        Create a config
        """
        pass

    def test_post_node_balancer_node(self) -> None:
        """Test case for post_node_balancer_node

        Create a node
        """
        pass

    def test_post_rebuild_node_balancer_config(self) -> None:
        """Test case for post_rebuild_node_balancer_config

        Rebuild a config
        """
        pass

    def test_put_node_balancer(self) -> None:
        """Test case for put_node_balancer

        Update a NodeBalancer
        """
        pass

    def test_put_node_balancer_config(self) -> None:
        """Test case for put_node_balancer_config

        Update a config
        """
        pass

    def test_put_node_balancer_node(self) -> None:
        """Test case for put_node_balancer_node

        Update a node
        """
        pass


if __name__ == '__main__':
    unittest.main()
