# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_invoices200_response_data_inner_tax_summary_inner import GetInvoices200ResponseDataInnerTaxSummaryInner

class TestGetInvoices200ResponseDataInnerTaxSummaryInner(unittest.TestCase):
    """GetInvoices200ResponseDataInnerTaxSummaryInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInvoices200ResponseDataInnerTaxSummaryInner:
        """Test GetInvoices200ResponseDataInnerTaxSummaryInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInvoices200ResponseDataInnerTaxSummaryInner`
        """
        model = GetInvoices200ResponseDataInnerTaxSummaryInner()
        if include_optional:
            return GetInvoices200ResponseDataInnerTaxSummaryInner(
                name = 'PA STATE TAX',
                tax = 12.25
            )
        else:
            return GetInvoices200ResponseDataInnerTaxSummaryInner(
        )
        """

    def testGetInvoices200ResponseDataInnerTaxSummaryInner(self):
        """Test GetInvoices200ResponseDataInnerTaxSummaryInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
