# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.added_get_entity_transfers200_all_of_entities import AddedGetEntityTransfers200AllOfEntities

class TestAddedGetEntityTransfers200AllOfEntities(unittest.TestCase):
    """AddedGetEntityTransfers200AllOfEntities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddedGetEntityTransfers200AllOfEntities:
        """Test AddedGetEntityTransfers200AllOfEntities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddedGetEntityTransfers200AllOfEntities`
        """
        model = AddedGetEntityTransfers200AllOfEntities()
        if include_optional:
            return AddedGetEntityTransfers200AllOfEntities(
                linodes = [111,222]
            )
        else:
            return AddedGetEntityTransfers200AllOfEntities(
        )
        """

    def testAddedGetEntityTransfers200AllOfEntities(self):
        """Test AddedGetEntityTransfers200AllOfEntities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
