# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_delete_client(self) -> None:
        """Test case for delete_client

        Delete an OAuth client
        """
        pass

    def test_delete_entity_transfer(self) -> None:
        """Test case for delete_entity_transfer

        Cancel an entity transfer
        """
        pass

    def test_delete_payment_method(self) -> None:
        """Test case for delete_payment_method

        Delete a payment method
        """
        pass

    def test_delete_service_transfer(self) -> None:
        """Test case for delete_service_transfer

        Cancel a service transfer
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete a user
        """
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        Get your account
        """
        pass

    def test_get_account_agreements(self) -> None:
        """Test case for get_account_agreements

        List agreements
        """
        pass

    def test_get_account_availability(self) -> None:
        """Test case for get_account_availability

        Get a region's service availability
        """
        pass

    def test_get_account_login(self) -> None:
        """Test case for get_account_login

        Get an account login
        """
        pass

    def test_get_account_logins(self) -> None:
        """Test case for get_account_logins

        List user logins
        """
        pass

    def test_get_account_settings(self) -> None:
        """Test case for get_account_settings

        Get account settings
        """
        pass

    def test_get_availability(self) -> None:
        """Test case for get_availability

        List available services
        """
        pass

    def test_get_child_account(self) -> None:
        """Test case for get_child_account

        Get a child account
        """
        pass

    def test_get_child_accounts(self) -> None:
        """Test case for get_child_accounts

        List child accounts
        """
        pass

    def test_get_client(self) -> None:
        """Test case for get_client

        Get an OAuth client
        """
        pass

    def test_get_client_thumbnail(self) -> None:
        """Test case for get_client_thumbnail

        Get the OAuth client's thumbnail
        """
        pass

    def test_get_clients(self) -> None:
        """Test case for get_clients

        List OAuth clients
        """
        pass

    def test_get_enrolled_beta_program(self) -> None:
        """Test case for get_enrolled_beta_program

        Get an enrolled Beta program
        """
        pass

    def test_get_enrolled_beta_programs(self) -> None:
        """Test case for get_enrolled_beta_programs

        List enrolled Beta programs
        """
        pass

    def test_get_entity_transfer(self) -> None:
        """Test case for get_entity_transfer

        Get an entity transfer
        """
        pass

    def test_get_entity_transfers(self) -> None:
        """Test case for get_entity_transfers

        List entity transfers
        """
        pass

    def test_get_event(self) -> None:
        """Test case for get_event

        Get an event
        """
        pass

    def test_get_events(self) -> None:
        """Test case for get_events

        List events
        """
        pass

    def test_get_invoice(self) -> None:
        """Test case for get_invoice

        Get an invoice
        """
        pass

    def test_get_invoice_items(self) -> None:
        """Test case for get_invoice_items

        List invoice items
        """
        pass

    def test_get_invoices(self) -> None:
        """Test case for get_invoices

        List invoices
        """
        pass

    def test_get_maintenance(self) -> None:
        """Test case for get_maintenance

        List maintenances
        """
        pass

    def test_get_notifications(self) -> None:
        """Test case for get_notifications

        List notifications
        """
        pass

    def test_get_payment(self) -> None:
        """Test case for get_payment

        Get a payment
        """
        pass

    def test_get_payment_method(self) -> None:
        """Test case for get_payment_method

        Get a payment method
        """
        pass

    def test_get_payment_methods(self) -> None:
        """Test case for get_payment_methods

        List payment methods
        """
        pass

    def test_get_payments(self) -> None:
        """Test case for get_payments

        List payments
        """
        pass

    def test_get_service_transfer(self) -> None:
        """Test case for get_service_transfer

        Get a service transfer request
        """
        pass

    def test_get_service_transfers(self) -> None:
        """Test case for get_service_transfers

        List service transfers
        """
        pass

    def test_get_transfer(self) -> None:
        """Test case for get_transfer

        Get network usage
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get a user
        """
        pass

    def test_get_user_grants(self) -> None:
        """Test case for get_user_grants

        List a user's grants
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        List users
        """
        pass

    def test_post_accept_entity_transfer(self) -> None:
        """Test case for post_accept_entity_transfer

        Accept an entity transfer
        """
        pass

    def test_post_accept_service_transfer(self) -> None:
        """Test case for post_accept_service_transfer

        Accept a service transfer
        """
        pass

    def test_post_account_agreements(self) -> None:
        """Test case for post_account_agreements

        Acknowledge agreements
        """
        pass

    def test_post_beta_program(self) -> None:
        """Test case for post_beta_program

        Enroll in a Beta program
        """
        pass

    def test_post_cancel_account(self) -> None:
        """Test case for post_cancel_account

        Cancel your account
        """
        pass

    def test_post_child_account_token(self) -> None:
        """Test case for post_child_account_token

        Create a proxy user token
        """
        pass

    def test_post_client(self) -> None:
        """Test case for post_client

        Create an OAuth client
        """
        pass

    def test_post_credit_card(self) -> None:
        """Test case for post_credit_card

        Add or edit a credit card
        """
        pass

    def test_post_enable_account_managed(self) -> None:
        """Test case for post_enable_account_managed

        Enable Linode Managed
        """
        pass

    def test_post_entity_transfer(self) -> None:
        """Test case for post_entity_transfer

        Create an entity transfer
        """
        pass

    def test_post_event_read(self) -> None:
        """Test case for post_event_read

        Mark an event as read
        """
        pass

    def test_post_event_seen(self) -> None:
        """Test case for post_event_seen

        Mark an event as seen
        """
        pass

    def test_post_execute_pay_pal_payment(self) -> None:
        """Test case for post_execute_pay_pal_payment

        Execute a PayPal payment
        """
        pass

    def test_post_make_payment_method_default(self) -> None:
        """Test case for post_make_payment_method_default

        Set a default payment method
        """
        pass

    def test_post_pay_pal_payment(self) -> None:
        """Test case for post_pay_pal_payment

        Stage a PayPal payment
        """
        pass

    def test_post_payment(self) -> None:
        """Test case for post_payment

        Make a payment
        """
        pass

    def test_post_payment_method(self) -> None:
        """Test case for post_payment_method

        Add a payment method
        """
        pass

    def test_post_promo_credit(self) -> None:
        """Test case for post_promo_credit

        Add a promo credit
        """
        pass

    def test_post_reset_client_secret(self) -> None:
        """Test case for post_reset_client_secret

        Reset an OAuth client secret
        """
        pass

    def test_post_service_transfer(self) -> None:
        """Test case for post_service_transfer

        Request a service transfer
        """
        pass

    def test_post_user(self) -> None:
        """Test case for post_user

        Create a user
        """
        pass

    def test_put_account(self) -> None:
        """Test case for put_account

        Update your account
        """
        pass

    def test_put_account_settings(self) -> None:
        """Test case for put_account_settings

        Update account settings
        """
        pass

    def test_put_client(self) -> None:
        """Test case for put_client

        Update an OAuth client
        """
        pass

    def test_put_client_thumbnail(self) -> None:
        """Test case for put_client_thumbnail

        Update the OAuth client's thumbnail
        """
        pass

    def test_put_user(self) -> None:
        """Test case for put_user

        Update a user
        """
        pass

    def test_put_user_grants(self) -> None:
        """Test case for put_user_grants

        Update a user's grants
        """
        pass


if __name__ == '__main__':
    unittest.main()
