# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_longview_types200_response_data_inner import GetLongviewTypes200ResponseDataInner

class TestGetLongviewTypes200ResponseDataInner(unittest.TestCase):
    """GetLongviewTypes200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLongviewTypes200ResponseDataInner:
        """Test GetLongviewTypes200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLongviewTypes200ResponseDataInner`
        """
        model = GetLongviewTypes200ResponseDataInner()
        if include_optional:
            return GetLongviewTypes200ResponseDataInner(
                id = 'longview-3',
                label = 'Longview Pro 3 pack',
                price = openapi_client.models.get_longview_types_200_response_data_inner_price.get_longview_types_200_response_data_inner_price(
                    hourly = 0.0015, 
                    monthly = 0.1, ),
                region_prices = [
                    openapi_client.models.get_lke_types_200_response_data_inner_region_prices_inner.get_lke_types_200_response_data_inner_region_prices_inner(
                        hourly = 0.00018, 
                        id = 'us-east', 
                        monthly = 0.12, )
                    ],
                transfer = 0
            )
        else:
            return GetLongviewTypes200ResponseDataInner(
        )
        """

    def testGetLongviewTypes200ResponseDataInner(self):
        """Test GetLongviewTypes200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
