# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_pay_pal_payment_request import PostPayPalPaymentRequest

class TestPostPayPalPaymentRequest(unittest.TestCase):
    """PostPayPalPaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPayPalPaymentRequest:
        """Test PostPayPalPaymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPayPalPaymentRequest`
        """
        model = PostPayPalPaymentRequest()
        if include_optional:
            return PostPayPalPaymentRequest(
                cancel_url = 'https://example.org',
                redirect_url = 'https://example.org',
                usd = '120.50'
            )
        else:
            return PostPayPalPaymentRequest(
                cancel_url = 'https://example.org',
                redirect_url = 'https://example.org',
                usd = '120.50',
        )
        """

    def testPostPayPalPaymentRequest(self):
        """Test PostPayPalPaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
