# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_linode_types200_response_data_inner import GetLinodeTypes200ResponseDataInner

class TestGetLinodeTypes200ResponseDataInner(unittest.TestCase):
    """GetLinodeTypes200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLinodeTypes200ResponseDataInner:
        """Test GetLinodeTypes200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLinodeTypes200ResponseDataInner`
        """
        model = GetLinodeTypes200ResponseDataInner()
        if include_optional:
            return GetLinodeTypes200ResponseDataInner(
                addons = openapi_client.models.get_linode_types_200_response_data_inner_addons.get_linode_types_200_response_data_inner_addons(
                    backups = openapi_client.models.get_linode_types_200_response_data_inner_addons_backups.get_linode_types_200_response_data_inner_addons_backups(
                        price = openapi_client.models.get_linode_types_200_response_data_inner_addons_backups_price.get_linode_types_200_response_data_inner_addons_backups_price(
                            hourly = 0.008, 
                            monthly = 5, ), 
                        region_prices = [
                            openapi_client.models.get_linode_types_200_response_data_inner_addons_backups_region_prices_inner.get_linode_types_200_response_data_inner_addons_backups_region_prices_inner(
                                hourly = 0.0096, 
                                id = 'us-east', 
                                monthly = 6, )
                            ], ), ),
                var_class = 'standard',
                disk = 81920,
                gpus = 0,
                id = 'g6-standard-2',
                label = 'Linode 4GB',
                memory = 4096,
                network_out = 1000,
                price = openapi_client.models.get_linode_types_200_response_data_inner_price.get_linode_types_200_response_data_inner_price(
                    hourly = 0.03, 
                    monthly = 20, ),
                region_prices = [
                    openapi_client.models.get_linode_types_200_response_data_inner_region_prices_inner.get_linode_types_200_response_data_inner_region_prices_inner(
                        hourly = 0.036, 
                        id = 'us-east', 
                        monthly = 24, )
                    ],
                successor = '',
                transfer = 4000,
                vcpus = 2
            )
        else:
            return GetLinodeTypes200ResponseDataInner(
        )
        """

    def testGetLinodeTypes200ResponseDataInner(self):
        """Test GetLinodeTypes200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
