# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.linode_instances_api import LinodeInstancesApi


class TestLinodeInstancesApi(unittest.TestCase):
    """LinodeInstancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinodeInstancesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_disk(self) -> None:
        """Test case for delete_disk

        Delete a disk
        """
        pass

    def test_delete_linode_config(self) -> None:
        """Test case for delete_linode_config

        Delete a config profile
        """
        pass

    def test_delete_linode_config_interface(self) -> None:
        """Test case for delete_linode_config_interface

        Delete a configuration profile interface
        """
        pass

    def test_delete_linode_instance(self) -> None:
        """Test case for delete_linode_instance

        Delete a Linode
        """
        pass

    def test_delete_linode_ip(self) -> None:
        """Test case for delete_linode_ip

        Delete an IPv4 address
        """
        pass

    def test_get_backup(self) -> None:
        """Test case for get_backup

        Get a backup
        """
        pass

    def test_get_backups(self) -> None:
        """Test case for get_backups

        List backups
        """
        pass

    def test_get_kernel(self) -> None:
        """Test case for get_kernel

        Get a kernel
        """
        pass

    def test_get_kernels(self) -> None:
        """Test case for get_kernels

        List kernels
        """
        pass

    def test_get_linode_config(self) -> None:
        """Test case for get_linode_config

        Get a config profile
        """
        pass

    def test_get_linode_config_interface(self) -> None:
        """Test case for get_linode_config_interface

        Get a configuration profile interface
        """
        pass

    def test_get_linode_config_interfaces(self) -> None:
        """Test case for get_linode_config_interfaces

        List configuration profile interfaces
        """
        pass

    def test_get_linode_configs(self) -> None:
        """Test case for get_linode_configs

        List config profiles
        """
        pass

    def test_get_linode_disk(self) -> None:
        """Test case for get_linode_disk

        Get a disk
        """
        pass

    def test_get_linode_disks(self) -> None:
        """Test case for get_linode_disks

        List disks
        """
        pass

    def test_get_linode_firewalls(self) -> None:
        """Test case for get_linode_firewalls

        List a Linode's firewalls
        """
        pass

    def test_get_linode_instance(self) -> None:
        """Test case for get_linode_instance

        Get a Linode
        """
        pass

    def test_get_linode_instances(self) -> None:
        """Test case for get_linode_instances

        List Linodes
        """
        pass

    def test_get_linode_ip(self) -> None:
        """Test case for get_linode_ip

        Get a Linode's IP address
        """
        pass

    def test_get_linode_ips(self) -> None:
        """Test case for get_linode_ips

        Get networking information
        """
        pass

    def test_get_linode_node_balancers(self) -> None:
        """Test case for get_linode_node_balancers

        List Linode NodeBalancers
        """
        pass

    def test_get_linode_stats(self) -> None:
        """Test case for get_linode_stats

        Get Linode statistics
        """
        pass

    def test_get_linode_stats_by_year_month(self) -> None:
        """Test case for get_linode_stats_by_year_month

        Get monthly statistics
        """
        pass

    def test_get_linode_transfer(self) -> None:
        """Test case for get_linode_transfer

        Get a network transfer
        """
        pass

    def test_get_linode_transfer_by_year_month(self) -> None:
        """Test case for get_linode_transfer_by_year_month

        Get monthly network transfer stats
        """
        pass

    def test_get_linode_type(self) -> None:
        """Test case for get_linode_type

        Get a type
        """
        pass

    def test_get_linode_types(self) -> None:
        """Test case for get_linode_types

        List types
        """
        pass

    def test_get_linode_volumes(self) -> None:
        """Test case for get_linode_volumes

        List a Linode's volumes
        """
        pass

    def test_post_add_linode_config(self) -> None:
        """Test case for post_add_linode_config

        Create a config profile
        """
        pass

    def test_post_add_linode_disk(self) -> None:
        """Test case for post_add_linode_disk

        Create a disk
        """
        pass

    def test_post_add_linode_ip(self) -> None:
        """Test case for post_add_linode_ip

        Allocate an IPv4 address
        """
        pass

    def test_post_apply_firewalls(self) -> None:
        """Test case for post_apply_firewalls

        Apply a Linode's firewalls
        """
        pass

    def test_post_boot_linode_instance(self) -> None:
        """Test case for post_boot_linode_instance

        Boot a Linode
        """
        pass

    def test_post_cancel_backups(self) -> None:
        """Test case for post_cancel_backups

        Cancel backups
        """
        pass

    def test_post_clone_linode_disk(self) -> None:
        """Test case for post_clone_linode_disk

        Clone a disk
        """
        pass

    def test_post_clone_linode_instance(self) -> None:
        """Test case for post_clone_linode_instance

        Clone a Linode
        """
        pass

    def test_post_enable_backups(self) -> None:
        """Test case for post_enable_backups

        Enable backups
        """
        pass

    def test_post_linode_config_interface(self) -> None:
        """Test case for post_linode_config_interface

        Add a configuration profile interface
        """
        pass

    def test_post_linode_config_interfaces(self) -> None:
        """Test case for post_linode_config_interfaces

        Reorder configuration profile interfaces
        """
        pass

    def test_post_linode_instance(self) -> None:
        """Test case for post_linode_instance

        Create a Linode
        """
        pass

    def test_post_migrate_linode_instance(self) -> None:
        """Test case for post_migrate_linode_instance

        Initiate a DC migration/pending host migration
        """
        pass

    def test_post_mutate_linode_instance(self) -> None:
        """Test case for post_mutate_linode_instance

        Upgrade a Linode
        """
        pass

    def test_post_reboot_linode_instance(self) -> None:
        """Test case for post_reboot_linode_instance

        Reboot a Linode
        """
        pass

    def test_post_rebuild_linode_instance(self) -> None:
        """Test case for post_rebuild_linode_instance

        Rebuild a Linode
        """
        pass

    def test_post_rescue_linode_instance(self) -> None:
        """Test case for post_rescue_linode_instance

        Boot a Linode into rescue mode
        """
        pass

    def test_post_reset_disk_password(self) -> None:
        """Test case for post_reset_disk_password

        Reset a disk root password
        """
        pass

    def test_post_reset_linode_password(self) -> None:
        """Test case for post_reset_linode_password

        Reset a Linode's root password
        """
        pass

    def test_post_resize_disk(self) -> None:
        """Test case for post_resize_disk

        Resize a disk
        """
        pass

    def test_post_resize_linode_instance(self) -> None:
        """Test case for post_resize_linode_instance

        Resize a Linode
        """
        pass

    def test_post_restore_backup(self) -> None:
        """Test case for post_restore_backup

        Restore a backup
        """
        pass

    def test_post_shutdown_linode_instance(self) -> None:
        """Test case for post_shutdown_linode_instance

        Shut down a Linode
        """
        pass

    def test_post_snapshot(self) -> None:
        """Test case for post_snapshot

        Create a snapshot
        """
        pass

    def test_put_disk(self) -> None:
        """Test case for put_disk

        Update a disk
        """
        pass

    def test_put_linode_config(self) -> None:
        """Test case for put_linode_config

        Update a config profile
        """
        pass

    def test_put_linode_config_interface(self) -> None:
        """Test case for put_linode_config_interface

        Update a configuration profile interface
        """
        pass

    def test_put_linode_instance(self) -> None:
        """Test case for put_linode_instance

        Update a Linode
        """
        pass

    def test_put_linode_ip(self) -> None:
        """Test case for put_linode_ip

        Update an IP address's RDNS for a Linode
        """
        pass


if __name__ == '__main__':
    unittest.main()
