# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_payment202_response import PostPayment202Response

class TestPostPayment202Response(unittest.TestCase):
    """PostPayment202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPayment202Response:
        """Test PostPayment202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPayment202Response`
        """
        model = PostPayment202Response()
        if include_optional:
            return PostPayment202Response(
                warnings = [
                    openapi_client.models.post_payment_202_response_warnings_inner.post_payment_202_response_warnings_inner(
                        details = 'Linode 123 could not be rebooted.', 
                        title = 'Unable to reboot Linode.', )
                    ]
            )
        else:
            return PostPayment202Response(
        )
        """

    def testPostPayment202Response(self):
        """Test PostPayment202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
