# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.network_transfer_prices_api import NetworkTransferPricesApi


class TestNetworkTransferPricesApi(unittest.TestCase):
    """NetworkTransferPricesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkTransferPricesApi()

    def tearDown(self) -> None:
        pass

    def test_get_network_transfer_prices(self) -> None:
        """Test case for get_network_transfer_prices

        List network transfer prices
        """
        pass


if __name__ == '__main__':
    unittest.main()
