# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_invoices200_response_data_inner import GetInvoices200ResponseDataInner

class TestGetInvoices200ResponseDataInner(unittest.TestCase):
    """GetInvoices200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInvoices200ResponseDataInner:
        """Test GetInvoices200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInvoices200ResponseDataInner`
        """
        model = GetInvoices200ResponseDataInner()
        if include_optional:
            return GetInvoices200ResponseDataInner(
                billing_source = 'linode',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 123,
                label = 'Invoice',
                subtotal = 120.25,
                tax = 12.25,
                tax_summary = [
                    openapi_client.models.get_invoices_200_response_data_inner_tax_summary_inner.get_invoices_200_response_data_inner_tax_summary_inner(
                        name = 'PA STATE TAX', 
                        tax = 12.25, )
                    ],
                total = 132.5
            )
        else:
            return GetInvoices200ResponseDataInner(
        )
        """

    def testGetInvoices200ResponseDataInner(self):
        """Test GetInvoices200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
