# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_backups200_response import GetBackups200Response

class TestGetBackups200Response(unittest.TestCase):
    """GetBackups200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBackups200Response:
        """Test GetBackups200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBackups200Response`
        """
        model = GetBackups200Response()
        if include_optional:
            return GetBackups200Response(
                automatic = [
                    null
                    ],
                snapshot = openapi_client.models.get_backups_200_response_snapshot.get_backups_200_response_snapshot(
                    current = openapi_client.models.get_backups_200_response_snapshot_current.get_backups_200_response_snapshot_current(
                        available = True, 
                        configs = [
                            'My Debian 9 Config'
                            ], 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        disks = [
                            openapi_client.models.get_backups_200_response_automatic_inner_all_of_disks_inner.get_backups_200_response_automatic_inner_allOf_disks_inner(
                                filesystem = 'ext4', 
                                label = 'My Debian 9 Disk', 
                                size = 9001, )
                            ], 
                        finished = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = 123456, 
                        label = 'Webserver-Backup-2018', 
                        status = 'successful', 
                        type = 'snapshot', 
                        updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    in_progress = openapi_client.models.get_backups_200_response_snapshot_current.get_backups_200_response_snapshot_current(
                        available = True, 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        finished = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = 123456, 
                        label = 'Webserver-Backup-2018', 
                        status = 'successful', 
                        type = 'snapshot', 
                        updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
            )
        else:
            return GetBackups200Response(
        )
        """

    def testGetBackups200Response(self):
        """Test GetBackups200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
