# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_profile200_response_referrals import GetProfile200ResponseReferrals

class TestGetProfile200ResponseReferrals(unittest.TestCase):
    """GetProfile200ResponseReferrals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProfile200ResponseReferrals:
        """Test GetProfile200ResponseReferrals
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProfile200ResponseReferrals`
        """
        model = GetProfile200ResponseReferrals()
        if include_optional:
            return GetProfile200ResponseReferrals(
                code = '871be32f49c1411b14f29f618aaf0c14637fb8d3',
                completed = 0,
                credit = 0,
                pending = 0,
                total = 0,
                url = 'https://www.linode.com/?r=871be32f49c1411b14f29f618aaf0c14637fb8d3'
            )
        else:
            return GetProfile200ResponseReferrals(
        )
        """

    def testGetProfile200ResponseReferrals(self):
        """Test GetProfile200ResponseReferrals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
