# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.added_get_user200_all_of_last_login import AddedGetUser200AllOfLastLogin

class TestAddedGetUser200AllOfLastLogin(unittest.TestCase):
    """AddedGetUser200AllOfLastLogin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddedGetUser200AllOfLastLogin:
        """Test AddedGetUser200AllOfLastLogin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddedGetUser200AllOfLastLogin`
        """
        model = AddedGetUser200AllOfLastLogin()
        if include_optional:
            return AddedGetUser200AllOfLastLogin(
                login_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'successful'
            )
        else:
            return AddedGetUser200AllOfLastLogin(
        )
        """

    def testAddedGetUser200AllOfLastLogin(self):
        """Test AddedGetUser200AllOfLastLogin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
