# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_stack_scripts200_response import GetStackScripts200Response

class TestGetStackScripts200Response(unittest.TestCase):
    """GetStackScripts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStackScripts200Response:
        """Test GetStackScripts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStackScripts200Response`
        """
        model = GetStackScripts200Response()
        if include_optional:
            return GetStackScripts200Response(
                data = [
                    openapi_client.models.get_stack_scripts_200_response_data_inner.get_stack_scripts_200_response_data_inner(
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deployments_active = 1, 
                        deployments_total = 12, 
                        description = 'This StackScript installs and configures MySQL', 
                        id = 10079, 
                        images = ["linode/debian9","linode/debian8"], 
                        is_public = True, 
                        label = 'a-stackscript', 
                        mine = True, 
                        rev_note = 'Set up MySQL', 
                        script = '\"#!/bin/bash\"', 
                        updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user_defined_fields = {"example":"hunter2","label":"Enter the DB password","name":"DB_PASSWORD"}, 
                        user_gravatar_id = 'a445b305abda30ebc766bc7fda037c37', 
                        username = 'myuser', )
                    ],
                page = 1,
                pages = 1,
                results = 1
            )
        else:
            return GetStackScripts200Response(
        )
        """

    def testGetStackScripts200Response(self):
        """Test GetStackScripts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
