# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetRegions200ResponseDataInnerPlacementGroupLimits(BaseModel):
    """
    The limits for [placement groups](https://www.linode.com/docs/products/compute/compute-instances/guides/placement-groups/) in this region.
    """ # noqa: E501
    maximum_linodes_per_pg: Optional[StrictInt] = Field(default=None, description="The maximum number of compute instances you can include in a single placement group in this region.")
    maximum_pgs_per_customer: Optional[StrictInt] = Field(default=None, description="The maximum number of placement groups you can have in this region. Displayed as `null` if you don't have a limit.")
    __properties: ClassVar[List[str]] = ["maximum_linodes_per_pg", "maximum_pgs_per_customer"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRegions200ResponseDataInnerPlacementGroupLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "maximum_linodes_per_pg",
            "maximum_pgs_per_customer",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if maximum_pgs_per_customer (nullable) is None
        # and model_fields_set contains the field
        if self.maximum_pgs_per_customer is None and "maximum_pgs_per_customer" in self.model_fields_set:
            _dict['maximum_pgs_per_customer'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRegions200ResponseDataInnerPlacementGroupLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "maximum_linodes_per_pg": obj.get("maximum_linodes_per_pg"),
            "maximum_pgs_per_customer": obj.get("maximum_pgs_per_customer")
        })
        return _obj


