# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.get_object_storage_bucket_content200_response_data_inner import GetObjectStorageBucketContent200ResponseDataInner
from typing import Optional, Set
from typing_extensions import Self

class GetObjectStorageBucketContent200Response(BaseModel):
    """
    GetObjectStorageBucketContent200Response
    """ # noqa: E501
    data: Optional[List[GetObjectStorageBucketContent200ResponseDataInner]] = None
    is_truncated: Optional[StrictBool] = Field(default=None, description="Designates if there is another page of bucket objects.")
    next_marker: Optional[StrictStr] = Field(default=None, description="Returns the value you should pass to the `marker` query parameter to get the next page of objects. If there is no next page, `null` will be returned.")
    __properties: ClassVar[List[str]] = ["data", "is_truncated", "next_marker"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetObjectStorageBucketContent200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # set to None if next_marker (nullable) is None
        # and model_fields_set contains the field
        if self.next_marker is None and "next_marker" in self.model_fields_set:
            _dict['next_marker'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetObjectStorageBucketContent200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data": [GetObjectStorageBucketContent200ResponseDataInner.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "is_truncated": obj.get("is_truncated"),
            "next_marker": obj.get("next_marker")
        })
        return _obj


