# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.post_object_storage_keys_request_bucket_access_inner import PostObjectStorageKeysRequestBucketAccessInner
from typing import Optional, Set
from typing_extensions import Self

class PostObjectStorageKeysRequest(BaseModel):
    """
    PostObjectStorageKeysRequest
    """ # noqa: E501
    bucket_access: Optional[List[PostObjectStorageKeysRequestBucketAccessInner]] = Field(default=None, description="Set up the key to limit access to specific buckets, each with a specific permission level. You can create a limited Object Storage key with access to no buckets. Include an empty `bucket_access` array in the request.")
    label: Optional[StrictStr] = Field(default=None, description="The label for the Object Storage key, for display purposes only.")
    regions: Optional[List[StrictStr]] = Field(default=None, description="You can use a key to create new buckets in regions set in this array. But it can't be used to manage content in those buckets. See [Create an Object Storage key](https://techdocs.akamai.com/linode-api/reference/post-object-storage-keys) for more details.")
    __properties: ClassVar[List[str]] = ["bucket_access", "label", "regions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostObjectStorageKeysRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bucket_access (list)
        _items = []
        if self.bucket_access:
            for _item_bucket_access in self.bucket_access:
                if _item_bucket_access:
                    _items.append(_item_bucket_access.to_dict())
            _dict['bucket_access'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostObjectStorageKeysRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bucket_access": [PostObjectStorageKeysRequestBucketAccessInner.from_dict(_item) for _item in obj["bucket_access"]] if obj.get("bucket_access") is not None else None,
            "label": obj.get("label"),
            "regions": obj.get("regions")
        })
        return _obj


