# coding: utf-8

"""
    Linode API

    [Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

    The version of the OpenAPI document: 4.189.2
    Contact: support@linode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PostCreditCardRequest(BaseModel):
    """
    An object representing the credit card information you have on file with Linode to make Payments against your Account.
    """ # noqa: E501
    card_number: Annotated[str, Field(min_length=14, strict=True, max_length=24)] = Field(description="Your credit card number. No spaces or hyphens (`-`) allowed.")
    cvv: Annotated[str, Field(min_length=3, strict=True, max_length=4)] = Field(description="CVV (Card Verification Value) of the credit card, typically found on the back of the card.")
    expiry_month: Annotated[int, Field(le=12, strict=True, ge=1)] = Field(description="A value from 1-12 representing the expiration month of your credit card.    - 1 = January   - 2 = February   - 3 = March   - Etc.")
    expiry_year: Annotated[int, Field(strict=True)] = Field(description="A four-digit integer representing the expiration year of your credit card.  The combination of `expiry_month` and `expiry_year` must result in a month/year combination of the current month or in the future. An expiration date set in the past is invalid.")
    __properties: ClassVar[List[str]] = ["card_number", "cvv", "expiry_month", "expiry_year"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostCreditCardRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostCreditCardRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "card_number": obj.get("card_number"),
            "cvv": obj.get("cvv"),
            "expiry_month": obj.get("expiry_month"),
            "expiry_year": obj.get("expiry_year")
        })
        return _obj


